version: 2

updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/.requirements" # Location of package manifests
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
