version: 2

updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    ignore:
      # Ignore updates to "black" because we'd need to reformat everything
      - dependency-name: "black"
