site_name: j-Wave

# Project info
site_name: j-Wave
site_author: Antonio Stanziola, Biomedical Ultrasound Group
site_description: >-
  Fast and differentiable acoustic simulations in JAX
site_url: https://ucl-bug.github.io/jwave/

theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.instant
    - content.code.annotate

nav:
  - Home: index.md
  - API:
    - acoustics: api_acoustics.md
    - extras: api_extras.md
    - geometry: api_geometry.md
    - phantoms: api_phantoms.md
    - signal_processing: api_signal_processing.md
    - utils: api_utils.md
  - Tutorials:
    - Initial value problems:
      - Homogeneous wave propagation: notebooks/ivp/homogeneous_medium.ipynb
      - Sensors: notebooks/ivp/homogeneous_medium_sensors.ipynb
      - Automatic differentiation: notebooks/ivp/homogeneous_medium_backprop.ipynb
    - Homogeneous medium IVP: notebooks/homog_propagation_medium.ipynb
    - Heterogeneous wave equation: notebooks/sim_wave_equation.ipynb
    - 3D Simulations: notebooks/homog_propagation_medium_3d.ipynb
    - Full wave inversion: notebooks/FWI.ipynb
    - Helmholtz equation: notebooks/helmholtz_problem.ipynb
    - Focusing single frequency waves: notebooks/helmholtz_solver_differentiable.ipynb
    - Linear uncertainty propagation: notebooks/uncertainty_propagation.ipynb
  - Benchmarks:
    - Accuracy vs k-Wave: benchmarks/homogeneous_vs_kwave.ipynb
    - Scaling vs timesteps: benchmarks/compute_time_vs_timesteps.ipynb
    - Scaling vs domain size (2D): benchmarks/compute_time_vs_size_2d.ipynb
    - Scaling vs domain size (3D): benchmarks/compute_time_vs_size_3d.ipynb
plugins:
  - mkdocs-jupyter
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
      custom_templates: templates
      watch:
        - jwave
  - search
  - mermaid2
  - macros:
      module_name: docs/macros

markdown_extensions:
  - toc:
      toc_depth: 5
  - markdown_katex:
      no_inline_svg: True
      insert_fonts_css: True
  - pymdownx.highlight
  - pymdownx.superfences:
       custom_fences:
         - name: mermaid
           class: mermaid
           format: !!python/name:pymdownx.superfences.fence_div_format

  - admonition
  - attr_list
  - footnotes

extra_css:
  - stylesheets/extra.css

extra_javascript:
    - https://unpkg.com/mermaid/dist/mermaid.min.js

use_directory_urls: false
