name: Documentation

on:
  push:
    tags:
      - '*'

jobs:

  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .requirements/requirements.txt
        pip install -r .requirements/requirements-docs.txt
        pip install -e .
    - name: Test and get accuracy file
      run: |
        echo "Testing and saving accuracy file..."
        make get_test_data
        coverage run --source=jwave -m pytest -vs
    - name: Build documentation
      run: mkdocs gh-deploy --force
